### ISSUE TITLE
I'm just going to leave this here...

### ISSUE THREAD

**Issue by antonzy** [shmoop207/appolo#5]
https://nestjs.com/
:)

**Comment by uditalias** [comment]
@antonzy And I'm just going to leave this benchmarks here...
:)

### NestJS
| name | average | min | max |
| - | - | - | - |
| Latency │ 24.58 │ 0 │ 428.714965 |
| Req/Sec │ 4035.55 │ 3530 │ **4661** |

### Appolo
| name | average | min | max |
| - | - | - | - |
| Latency │ 2.9 │ 0 │ 168.358889 |
| Req/Sec │ 33687.2 │ 27004 │ **35396** |
